"""
Markdown Generator

Takes the parsed solution data dict and produces a dict of
{filename: markdown_content} ready to be zipped and returned.
"""
from typing import Any


def generate_docs(parsed: dict[str, Any]) -> dict[str, str]:
    """Generate all Markdown documentation files. Returns {filename: content}."""
    docs: dict[str, str] = {}

    solution = parsed.get("solution", {})
    solution_name = solution.get("unique_name", "solution")

    docs["README.md"] = _generate_index(parsed, solution_name)
    docs["solution-overview.md"] = _generate_solution_overview(solution)
    docs["entities.md"] = _generate_entities(parsed.get("customizations", {}))
    docs["workflows.md"] = _generate_workflows(parsed.get("workflows", []))
    docs["web-resources.md"] = _generate_webresources(parsed.get("webresources", []))
    docs["environment-variables.md"] = _generate_env_vars(parsed.get("env_vars", []))
    docs["plugins.md"] = _generate_plugins(parsed.get("plugins", []))

    return docs


# ---- Index ---------------------------------------------------------------

def _generate_index(parsed: dict[str, Any], solution_name: str) -> str:
    sol = parsed.get("solution", {})
    lines = [
        f"# {solution_name} — Solution Documentation",
        "",
        f"> Generated by **Dataverse Solution Documenter**",
        "",
        "## Contents",
        "",
        "| Document | Description |",
        "|---|---|",
        "| [Solution Overview](solution-overview.md) | Metadata, publisher, version |",
        "| [Entities & Tables](entities.md) | All entities, attributes, forms, views |",
        "| [Workflows](workflows.md) | Classic and modern workflows |",
        "| [Web Resources](web-resources.md) | JS, HTML, CSS, and other web resources |",
        "| [Environment Variables](environment-variables.md) | Environment variable definitions |",
        "| [Plugins](plugins.md) | Plugin assemblies and step registrations |",
        "",
        "---",
        "",
        f"**Solution:** `{sol.get('unique_name', 'N/A')}`  ",
        f"**Version:** `{sol.get('version', 'N/A')}`  ",
        f"**Publisher:** {sol.get('publisher_name', 'N/A')}  ",
        f"**Managed:** {sol.get('is_managed', 'N/A')}  ",
    ]
    return "\n".join(lines)


# ---- Solution Overview ---------------------------------------------------

def _generate_solution_overview(solution: dict[str, Any]) -> str:
    lines = [
        "# Solution Overview",
        "",
        "| Field | Value |",
        "|---|---|",
        f"| Unique Name | `{solution.get('unique_name', '')}` |",
        f"| Version | `{solution.get('version', '')}` |",
        f"| Publisher | {solution.get('publisher_name', '')} |",
        f"| Publisher Prefix | `{solution.get('publisher_prefix', '')}` |",
        f"| Managed | {solution.get('is_managed', '')} |",
        f"| Root Components | {solution.get('component_count', 0)} |",
        "",
    ]
    if solution.get("description"):
        lines += ["## Description", "", solution["description"], ""]
    return "\n".join(lines)


# ---- Entities ------------------------------------------------------------

def _generate_entities(customizations: dict[str, Any]) -> str:
    entities = customizations.get("entities", [])
    lines = ["# Entities & Tables", ""]

    if not entities:
        lines.append("_No entities found in customizations.xml._")
        return "\n".join(lines)

    lines += [
        f"**Total entities:** {len(entities)}",
        "",
    ]

    for entity in entities:
        name = entity.get("display_name") or entity.get("name", "Unknown")
        schema = entity.get("name", "")
        lines += [
            f"## {name}",
            "",
            f"**Schema name:** `{schema}`  ",
            f"**Attributes:** {len(entity.get('attributes', []))}  ",
            f"**Forms:** {len(entity.get('forms', []))}  ",
            f"**Views:** {len(entity.get('views', []))}  ",
            f"**Relationships:** {len(entity.get('relationships', []))}  ",
            "",
        ]

        attrs = entity.get("attributes", [])
        if attrs:
            lines += ["### Attributes", "", "| Schema Name | Display Name | Type |", "|---|---|---|"]
            for attr in attrs:
                lines.append(
                    f"| `{attr.get('name', '')}` | {attr.get('display_name', '')} | {attr.get('type', '')} |"
                )
            lines.append("")

        forms = entity.get("forms", [])
        if forms:
            lines += ["### Forms", "", "| Name | Type |", "|---|---|"]
            for form in forms:
                lines.append(f"| {form.get('name', '')} | {form.get('type', '')} |")
            lines.append("")

        views = entity.get("views", [])
        if views:
            lines += ["### Views", "", "| Name |", "|---|"]
            for view in views:
                lines.append(f"| {view.get('name', '')} |")
            lines.append("")

        rels = entity.get("relationships", [])
        if rels:
            lines += ["### Relationships", "", "| Name | Type |", "|---|---|"]
            for rel in rels:
                lines.append(f"| `{rel.get('name', '')}` | {rel.get('type', '')} |")
            lines.append("")

        lines.append("---")
        lines.append("")

    return "\n".join(lines)


# ---- Workflows -----------------------------------------------------------

def _generate_workflows(workflows: list[dict[str, Any]]) -> str:
    lines = ["# Workflows", ""]

    if not workflows:
        lines.append("_No workflows found in this solution._")
        return "\n".join(lines)

    lines += [
        f"**Total workflows:** {len(workflows)}",
        "",
        "| Name | Primary Entity | Trigger | Category |",
        "|---|---|---|---|",
    ]
    for wf in workflows:
        lines.append(
            f"| {wf.get('name', '')} | {wf.get('primary_entity', '')} | {wf.get('trigger', '')} | {wf.get('category', '')} |"
        )

    lines.append("")
    return "\n".join(lines)


# ---- Web Resources -------------------------------------------------------

def _generate_webresources(webresources: list[dict[str, Any]]) -> str:
    lines = ["# Web Resources", ""]

    if not webresources:
        lines.append("_No web resources found in this solution._")
        return "\n".join(lines)

    lines += [
        f"**Total web resources:** {len(webresources)}",
        "",
        "| Name | Type | Path | Size |",
        "|---|---|---|---|",
    ]
    for wr in webresources:
        size_kb = f"{wr.get('size_bytes', 0) / 1024:.1f} KB"
        lines.append(
            f"| `{wr.get('name', '')}` | {wr.get('type', '')} | `{wr.get('path', '')}` | {size_kb} |"
        )

    lines.append("")
    return "\n".join(lines)


# ---- Environment Variables -----------------------------------------------

def _generate_env_vars(env_vars: list[dict[str, Any]]) -> str:
    lines = ["# Environment Variables", ""]

    if not env_vars:
        lines.append("_No environment variables found in this solution._")
        return "\n".join(lines)

    lines += [
        f"**Total environment variables:** {len(env_vars)}",
        "",
        "| Schema Name | Display Name | Type | Default Value | Description |",
        "|---|---|---|---|---|",
    ]
    for ev in env_vars:
        lines.append(
            f"| `{ev.get('schema_name', '')}` | {ev.get('display_name', '')} | {ev.get('type', '')} | `{ev.get('default_value', '')}` | {ev.get('description', '')} |"
        )

    lines.append("")
    return "\n".join(lines)


# ---- Plugins -------------------------------------------------------------

def _generate_plugins(plugins: list[dict[str, Any]]) -> str:
    lines = ["# Plugin Assemblies", ""]

    if not plugins:
        lines.append("_No plugin assemblies found in this solution._")
        return "\n".join(lines)

    lines.append(f"**Total assemblies:** {len(plugins)}")
    lines.append("")

    for plugin in plugins:
        lines += [
            f"## {plugin.get('name', 'Unknown Assembly')}",
            "",
            f"**Version:** `{plugin.get('version', '')}` | **Isolation:** {plugin.get('isolation_mode', '')}",
            "",
        ]
        if plugin.get("description"):
            lines += [plugin["description"], ""]

        steps = plugin.get("steps", [])
        if steps:
            lines += ["### Step Registrations", "", "| Name | Message | Stage | Mode | Primary Entity |", "|---|---|---|---|---|"]
            for step in steps:
                lines.append(
                    f"| {step.get('name', '')} | {step.get('message', '')} | {step.get('stage', '')} | {step.get('mode', '')} | {step.get('primary_entity', '')} |"
                )
            lines.append("")

        lines.append("---")
        lines.append("")

    return "\n".join(lines)
