"""
Markdown Generator

Takes the parsed solution data dict and produces a dict of
{filename: markdown_content} ready to be zipped and returned.
"""
from typing import Any


def generate_docs(parsed: dict[str, Any]) -> dict[str, str]:
    """Generate all Markdown documentation files. Returns {filename: content}."""
    solution = parsed.get("solution", {})
    solution_name = solution.get("unique_name", "solution")

    docs: dict[str, str] = {
        "README.md": _generate_index(parsed, solution_name),
        "solution-overview.md": _generate_solution_overview(solution),
        "entities.md": _generate_entities(parsed.get("entities", [])),
        "workflows.md": _generate_workflows(parsed.get("workflows", [])),
        "web-resources.md": _generate_webresources(parsed.get("webresources", [])),
        "environment-variables.md": _generate_env_vars(parsed.get("env_vars", [])),
        "security-roles.md": _generate_roles(
            parsed.get("roles", []),
            solution_entities=[e["name"] for e in parsed.get("entities", [])],
        ),
        "relationships.md": _generate_relationships(parsed.get("entity_relationships", [])),
        "connection-references.md": _generate_connection_refs(
            parsed.get("connection_references", [])
        ),
        "app-modules.md": _generate_app_modules(parsed.get("app_modules", [])),
    }

    plugins = parsed.get("plugins", [])
    if plugins:
        docs["plugins.md"] = _generate_plugins(plugins)

    option_sets = parsed.get("global_option_sets", [])
    if option_sets:
        docs["global-option-sets.md"] = _generate_global_option_sets(option_sets)

    return docs


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _h(level: int, text: str) -> str:
    return f"{'#' * level} {text}"


def _table(headers: list[str], rows: list[list[str]]) -> str:
    header_row = "| " + " | ".join(headers) + " |"
    sep_row = "|" + "|".join(["---"] * len(headers)) + "|"
    data_rows = ["| " + " | ".join(str(c) for c in row) + " |" for row in rows]
    return "\n".join([header_row, sep_row] + data_rows)


def _badge(text: str) -> str:
    return f"`{text}`"


# ---------------------------------------------------------------------------
# Index / README
# ---------------------------------------------------------------------------

def _generate_index(parsed: dict[str, Any], solution_name: str) -> str:
    sol = parsed.get("solution", {})
    lines = [
        _h(1, f"{sol.get('display_name', solution_name)} — Solution Documentation"),
        "",
        "> Generated by **Dataverse Solution Documenter**",
        "",
        _h(2, "Contents"),
        "",
        _table(
            ["Document", "Description"],
            [
                ["[Solution Overview](solution-overview.md)", "Metadata, publisher, version, component summary"],
                ["[Entities & Tables](entities.md)", f"Entities ({len(parsed.get('entities', []))})"],
                ["[Workflows](workflows.md)", f"Workflows ({len(parsed.get('workflows', []))})"],
                ["[Web Resources](web-resources.md)", f"Web resources ({len(parsed.get('webresources', []))})"],
                ["[Environment Variables](environment-variables.md)", f"Environment variable definitions ({len(parsed.get('env_vars', []))})"],
                ["[Security Roles](security-roles.md)", f"Roles ({len(parsed.get('roles', []))})"],
                ["[Entity Relationships](relationships.md)", f"Relationships ({len(parsed.get('entity_relationships', []))})"],
                ["[Connection References](connection-references.md)", f"Connection references ({len(parsed.get('connection_references', []))})"],
                ["[App Modules](app-modules.md)", f"Model-driven apps ({len(parsed.get('app_modules', []))})"],
            ],
        ),
        "",
        "---",
        "",
        f"**Solution:** {_badge(sol.get('unique_name', 'N/A'))}  ",
        f"**Version:** {_badge(sol.get('version', 'N/A'))}  ",
        f"**Publisher:** {sol.get('publisher_name', 'N/A')} ({_badge(sol.get('publisher_prefix', ''))})  ",
        f"**Managed:** {'Yes' if sol.get('is_managed') == '1' else 'No'}  ",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Solution Overview
# ---------------------------------------------------------------------------

def _generate_solution_overview(solution: dict[str, Any]) -> str:
    lines = [
        _h(1, "Solution Overview"),
        "",
        _h(2, "Metadata"),
        "",
        _table(
            ["Field", "Value"],
            [
                ["Unique Name", _badge(solution.get("unique_name", ""))],
                ["Display Name", solution.get("display_name", "")],
                ["Version", _badge(solution.get("version", ""))],
                ["Managed", "Yes" if solution.get("is_managed") == "1" else "No"],
                ["Publisher", solution.get("publisher_name", "")],
                ["Publisher Unique Name", _badge(solution.get("publisher_unique_name", ""))],
                ["Customization Prefix", _badge(solution.get("publisher_prefix", ""))],
                ["Option Value Prefix", solution.get("publisher_option_prefix", "")],
                ["Total Root Components", str(solution.get("component_count", 0))],
            ],
        ),
        "",
    ]

    if solution.get("description"):
        lines += [_h(2, "Description"), "", solution["description"], ""]

    if solution.get("publisher_description"):
        lines += [_h(2, "Publisher Description"), "", solution["publisher_description"], ""]

    component_types = solution.get("component_types", {})
    if component_types:
        lines += [
            _h(2, "Component Breakdown"),
            "",
            _table(
                ["Component Type", "Count"],
                [[ctype, str(count)] for ctype, count in sorted(component_types.items())],
            ),
            "",
        ]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Entities
# ---------------------------------------------------------------------------

def _generate_entities(entities: list[dict[str, Any]]) -> str:
    lines = [_h(1, "Entities & Tables"), ""]

    if not entities:
        lines.append("_No entities found in customizations.xml._")
        return "\n".join(lines)

    lines += [f"**Total entities:** {len(entities)}", ""]

    # Summary table
    lines += [
        _h(2, "Summary"),
        "",
        _table(
            ["Display Name", "Schema Name", "Attributes", "Forms", "Views"],
            [
                [
                    f"[{e.get('display_name') or e.get('name', '')}](#{(e.get('display_name') or e.get('name', '')).lower().replace(' ', '-').replace('_', '-')})",
                    _badge(e.get("name", "")),
                    str(len(e.get("attributes", []))),
                    str(len(e.get("forms", []))),
                    str(len(e.get("views", []))),
                ]
                for e in entities
            ],
        ),
        "",
        "---",
        "",
    ]

    for entity in entities:
        display = entity.get("display_name") or entity.get("name", "Unknown")
        schema = entity.get("name", "")
        lines += [_h(2, display), ""]

        lines += [
            _table(
                ["Field", "Value"],
                [
                    ["Schema Name", _badge(schema)],
                    ["Display Name", display],
                    ["Collection Name", entity.get("collection_name", "")],
                    ["Description", entity.get("description", "")],
                ],
            ),
            "",
        ]

        attrs = entity.get("attributes", [])
        if attrs:
            lines += [_h(3, "Attributes"), ""]
            attr_rows = []
            for attr in attrs:
                req = attr.get("required", "none")
                req_icon = "✅" if req == "required" else ("⚠️" if req == "systemrequired" else "")
                options_str = ""
                if attr.get("options"):
                    options_str = "; ".join(
                        f"{o['value']}: {o['label']}" for o in attr["options"][:5]
                    )
                    if len(attr["options"]) > 5:
                        options_str += f" (+{len(attr['options'])-5} more)"
                attr_rows.append([
                    _badge(attr.get("name", "")),
                    attr.get("display_name", ""),
                    attr.get("type", ""),
                    req_icon or req,
                    options_str,
                ])
            lines += [
                _table(["Schema Name", "Display Name", "Type", "Required", "Options"], attr_rows),
                "",
            ]

        forms = entity.get("forms", [])
        if forms:
            lines += [
                _h(3, "Forms"),
                "",
                _table(
                    ["Name", "ID", "Version", "Active"],
                    [
                        [
                            f.get("name", ""),
                            _badge(f.get("id", "")),
                            f.get("version", ""),
                            "✅" if f.get("active") else "❌",
                        ]
                        for f in forms
                    ],
                ),
                "",
            ]

        views = entity.get("views", [])
        if views:
            lines += [
                _h(3, "Views"),
                "",
                _table(
                    ["Name", "Type"],
                    [[v.get("name", ""), v.get("type", "")] for v in views],
                ),
                "",
            ]

        lines += ["---", ""]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Workflows
# ---------------------------------------------------------------------------

def _generate_workflows(workflows: list[dict[str, Any]]) -> str:
    lines = [_h(1, "Workflows"), ""]

    if not workflows:
        lines.append("_No workflows found in this solution._")
        return "\n".join(lines)

    lines += [f"**Total workflows:** {len(workflows)}", ""]

    # Group by category
    by_category: dict[str, list] = {}
    for wf in workflows:
        cat = wf.get("category", "Unknown")
        by_category.setdefault(cat, []).append(wf)

    for category, wfs in sorted(by_category.items()):
        lines += [_h(2, category), ""]
        for wf in wfs:
            lines += [_h(3, wf.get("name", "Unnamed")), ""]

            rows: list[list[str]] = [
                ["Category", wf.get("category", "")],
                ["Primary Entity", wf.get("primary_entity", "") or "N/A"],
                ["State", wf.get("state", "")],
                ["Introduced Version", wf.get("introduced_version", "")],
            ]
            if wf.get("description"):
                rows.insert(0, ["Description", wf["description"]])

            trigger_flags = []
            if wf.get("on_demand"):
                trigger_flags.append("On Demand")
            if wf.get("trigger_on_create"):
                trigger_flags.append("On Create")
            if wf.get("trigger_on_delete"):
                trigger_flags.append("On Delete")
            if trigger_flags:
                rows.append(["Classic Trigger", ", ".join(trigger_flags)])

            lines += [_table(["Field", "Value"], rows), ""]

            if wf.get("triggers"):
                lines += [
                    f"**Triggers:** {', '.join(_badge(t) for t in wf['triggers'])}  ",
                ]
            if wf.get("actions"):
                lines += [
                    f"**Actions:** {', '.join(_badge(a) for a in wf['actions'])}  ",
                ]
            if wf.get("connection_refs"):
                lines += [
                    f"**Connection References:** {', '.join(_badge(c) for c in wf['connection_refs'])}  ",
                ]

            if wf.get("file"):
                lines += [f"**Source File:** `{wf['file']}`  "]

            lines.append("")

        lines += ["---", ""]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Web Resources
# ---------------------------------------------------------------------------

def _generate_webresources(webresources: list[dict[str, Any]]) -> str:
    lines = [_h(1, "Web Resources"), ""]

    if not webresources:
        lines.append("_No web resources found in this solution._")
        return "\n".join(lines)

    lines += [f"**Total web resources:** {len(webresources)}", ""]

    lines += [
        _table(
            ["Name", "Display Name", "Type", "Size", "Introduced Version"],
            [
                [
                    _badge(wr.get("name", "")),
                    wr.get("display_name", ""),
                    wr.get("type", ""),
                    f"{wr.get('size_bytes', 0) / 1024:.1f} KB" if wr.get("size_bytes") else "—",
                    wr.get("introduced_version", ""),
                ]
                for wr in webresources
            ],
        ),
        "",
    ]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Environment Variables
# ---------------------------------------------------------------------------

def _generate_env_vars(env_vars: list[dict[str, Any]]) -> str:
    lines = [_h(1, "Environment Variables"), ""]

    if not env_vars:
        lines.append("_No environment variables found in this solution._")
        return "\n".join(lines)

    lines += [f"**Total environment variables:** {len(env_vars)}", ""]

    for ev in env_vars:
        lines += [_h(2, ev.get("display_name") or ev.get("schema_name", "Unknown")), ""]

        rows = [
            ["Schema Name", _badge(ev.get("schema_name", ""))],
            ["Display Name", ev.get("display_name", "")],
            ["Type", ev.get("type", "")],
            ["Required", "Yes" if ev.get("is_required") else "No"],
            ["Secret", "Yes" if ev.get("is_secret") else "No"],
            ["Introduced Version", ev.get("introduced_version", "")],
        ]
        if ev.get("description"):
            rows.insert(2, ["Description", ev["description"]])

        lines += [_table(["Field", "Value"], rows), "", "---", ""]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Security Roles
# ---------------------------------------------------------------------------

# Access level display: symbol + label
_LEVEL_SYMBOL = {
    "Global":  "🌐 Global",
    "Deep":    "🔵 Deep",
    "Local":   "🟡 Local",
    "Basic":   "🟢 Basic",
    "None":    "⬜ None",
}
_LEVEL_RANK = {"Global": 4, "Deep": 3, "Local": 2, "Basic": 1, "None": 0, "": -1}

_ACTIONS = ["Create", "Read", "Write", "Delete", "Append", "AppendTo", "Assign", "Share"]


def _level(val: str) -> str:
    return _LEVEL_SYMBOL.get(val, val or "—")


def _generate_roles(roles: list[dict[str, Any]], solution_entities: list[str] | None = None) -> str:
    lines = [_h(1, "Security Roles"), ""]

    if not roles:
        lines.append("_No security roles found in this solution._")
        return "\n".join(lines)

    lines += [
        f"**Total security roles:** {len(roles)}",
        "",
        "| Level | Meaning |",
        "|---|---|",
        "| 🌐 Global | Entire organisation |",
        "| 🔵 Deep | Business unit + child units |",
        "| 🟡 Local | Own business unit only |",
        "| 🟢 Basic | Records owned by the user |",
        "",
        "---",
        "",
    ]

    # ---- Section 1: Cross-role comparison for solution entities ----
    sol_ents = solution_entities or []
    if sol_ents and len(roles) > 1:
        lines += [
            _h(2, "Cross-Role Comparison — Solution Entities"),
            "",
            "> Showing **Read** access level per role for entities defined in this solution.",
            "",
        ]
        role_names = [r["name"] for r in roles]
        header = ["Entity"] + role_names
        sep = ["---"] * len(header)
        rows = []
        for ent in sol_ents:
            row = [f"`{ent}`"]
            for role in roles:
                ep = role.get("entity_privileges", {})
                # Case-insensitive lookup
                match = next(
                    (ep[k] for k in ep if k.lower() == ent.lower()), {}
                )
                read_level = match.get("Read", "—")
                row.append(_level(read_level) if read_level != "—" else "—")
            rows.append(row)

        lines.append("| " + " | ".join(header) + " |")
        lines.append("|" + "|".join(sep) + "|")
        for row in rows:
            lines.append("| " + " | ".join(row) + " |")
        lines += ["", "---", ""]

    # ---- Section 2: Full entity privilege matrix per role ----
    for role in roles:
        role_name = role.get("name", "Unknown")
        ep: dict[str, dict[str, str]] = role.get("entity_privileges", {})
        misc: dict[str, str] = role.get("misc_privileges", {})

        lines += [_h(2, role_name), ""]

        # -- 2a: Solution entities full CRUD matrix --
        if sol_ents:
            lines += [
                _h(3, "Solution Entities"),
                "",
                "| Entity | " + " | ".join(_ACTIONS) + " |",
                "|---|" + "|".join(["---"] * len(_ACTIONS)) + "|",
            ]
            for ent in sol_ents:
                match = next((ep[k] for k in ep if k.lower() == ent.lower()), {})
                cells = [_level(match.get(a, "")) if match.get(a) else "—" for a in _ACTIONS]
                lines.append(f"| `{ent}` | " + " | ".join(cells) + " |")
            lines.append("")

        # -- 2b: All other entities grouped by access level --
        lines += [_h(3, "All Entity Privileges"), ""]

        # Separate solution entities from others, group remainder by level profile
        sol_ents_lower = {e.lower() for e in sol_ents}
        other_entities = {k: v for k, v in ep.items() if k.lower() not in sol_ents_lower}

        if other_entities:
            # Group by highest access level (Read if present, else max of all)
            by_level: dict[str, list[tuple[str, dict]]] = {
                "Global": [], "Deep": [], "Local": [], "Basic": [], "Other": []
            }
            for ent_name, actions in sorted(other_entities.items()):
                read_level = actions.get("Read", "")
                top_level = read_level or max(
                    actions.values(),
                    key=lambda x: _LEVEL_RANK.get(x, -1),
                    default=""
                )
                bucket = top_level if top_level in by_level else "Other"
                by_level[bucket].append((ent_name, actions))

            for level_name, ents in by_level.items():
                if not ents:
                    continue
                lines += [
                    f"**{_LEVEL_SYMBOL.get(level_name, level_name)} access** ({len(ents)} entities)",
                    "",
                    "<details><summary>Expand</summary>",
                    "",
                    "| Entity | " + " | ".join(_ACTIONS) + " |",
                    "|---|" + "|".join(["---"] * len(_ACTIONS)) + "|",
                ]
                for ent_name, actions in ents:
                    cells = [_level(actions.get(a, "")) if actions.get(a) else "—" for a in _ACTIONS]
                    lines.append(f"| `{ent_name}` | " + " | ".join(cells) + " |")
                lines += ["", "</details>", ""]
        else:
            lines.append("_No additional entity privileges._\n")

        # -- 2c: Misc / non-entity privileges --
        if misc:
            lines += [
                _h(3, "Miscellaneous Privileges"),
                "",
                f"**{len(misc)} non-entity privileges** (feature access, system actions)",
                "",
                "| Privilege | Level |",
                "|---|---|",
            ]
            for priv_name, level in sorted(misc.items()):
                lines.append(f"| {priv_name} | {_level(level)} |")
            lines.append("")

        # -- 2d: Summary counts --
        total_entity_privs = sum(len(v) for v in ep.values())
        lines += [
            _h(3, "Summary"),
            "",
            _table(
                ["Metric", "Count"],
                [
                    ["Entities with privileges", str(len(ep))],
                    ["Total entity privilege grants", str(total_entity_privs)],
                    ["Miscellaneous privilege grants", str(len(misc))],
                ],
            ),
            "",
            "---",
            "",
        ]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Entity Relationships
# ---------------------------------------------------------------------------

def _generate_relationships(relationships: list[dict[str, Any]]) -> str:
    lines = [_h(1, "Entity Relationships"), ""]

    if not relationships:
        lines.append("_No entity relationships found in this solution._")
        return "\n".join(lines)

    lines += [f"**Total relationships:** {len(relationships)}", ""]

    lines += [
        _table(
            ["Relationship Name", "Type", "Entity 1", "Entity 2"],
            [
                [
                    _badge(r.get("name", "")),
                    r.get("type", ""),
                    _badge(r.get("entity1", "")) if r.get("entity1") else "—",
                    _badge(r.get("entity2", "")) if r.get("entity2") else "—",
                ]
                for r in relationships
            ],
        ),
        "",
    ]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Connection References
# ---------------------------------------------------------------------------

def _generate_connection_refs(refs: list[dict[str, Any]]) -> str:
    lines = [_h(1, "Connection References"), ""]

    if not refs:
        lines.append("_No connection references found in this solution._")
        return "\n".join(lines)

    lines += [
        f"**Total connection references:** {len(refs)}",
        "",
        _table(
            ["Logical Name", "Display Name", "Connector"],
            [
                [
                    _badge(r.get("logical_name", "")),
                    r.get("display_name", ""),
                    _badge(r.get("connector_id", "")) if r.get("connector_id") else "—",
                ]
                for r in refs
            ],
        ),
        "",
    ]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# App Modules
# ---------------------------------------------------------------------------

def _generate_app_modules(apps: list[dict[str, Any]]) -> str:
    lines = [_h(1, "Model-Driven Apps (App Modules)"), ""]

    if not apps:
        lines.append("_No app modules found in this solution._")
        return "\n".join(lines)

    for app in apps:
        lines += [_h(2, app.get("display_name") or app.get("unique_name", "Unknown")), ""]
        rows = [
            ["Unique Name", _badge(app.get("unique_name", ""))],
            ["Display Name", app.get("display_name", "")],
        ]
        if app.get("description"):
            rows.append(["Description", app["description"]])
        lines += [_table(["Field", "Value"], rows), "", "---", ""]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Global Option Sets
# ---------------------------------------------------------------------------

def _generate_global_option_sets(option_sets: list[dict[str, Any]]) -> str:
    lines = [_h(1, "Global Option Sets"), ""]

    if not option_sets:
        lines.append("_No global option sets found in this solution._")
        return "\n".join(lines)

    for os_data in option_sets:
        name = os_data.get("display_name") or os_data.get("name", "Unknown")
        lines += [_h(2, name), ""]
        if os_data.get("options"):
            lines += [
                _table(["Value", "Label"], [[o["value"], o["label"]] for o in os_data["options"]]),
                "",
            ]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Plugins
# ---------------------------------------------------------------------------

def _generate_plugins(plugins: list[dict[str, Any]]) -> str:
    lines = [_h(1, "Plugin Assemblies"), ""]

    if not plugins:
        lines.append("_No plugin assemblies found in this solution._")
        return "\n".join(lines)

    lines.append(f"**Total assemblies:** {len(plugins)}")
    lines.append("")

    for plugin in plugins:
        lines += [_h(2, plugin.get("name", "Unknown Assembly")), ""]
        lines += [
            _table(
                ["Field", "Value"],
                [
                    ["Version", _badge(plugin.get("version", ""))],
                    ["Isolation Mode", plugin.get("isolation_mode", "")],
                    ["Description", plugin.get("description", "")],
                ],
            ),
            "",
        ]

        steps = plugin.get("steps", [])
        if steps:
            lines += [
                _h(3, "Step Registrations"),
                "",
                _table(
                    ["Name", "Message", "Stage", "Mode", "Primary Entity"],
                    [
                        [
                            s.get("name", ""),
                            s.get("message", ""),
                            s.get("stage", ""),
                            s.get("mode", ""),
                            s.get("primary_entity", ""),
                        ]
                        for s in steps
                    ],
                ),
                "",
            ]

        lines += ["---", ""]

    return "\n".join(lines)
