"""
Markdown Generator

Takes the parsed solution data dict and produces a dict of
{filename: markdown_content} ready to be zipped and returned.
"""
from typing import Any


def generate_docs(parsed: dict[str, Any], warnings: list[str] | None = None) -> dict[str, str]:
    """Generate all Markdown documentation files. Returns {filename: content}."""
    solution = parsed.get("solution", {})
    solution_name = solution.get("unique_name", "solution")

    docs: dict[str, str] = {
        "README.md": _generate_index(parsed, solution_name, warnings=warnings),
        "solution-overview.md": _generate_solution_overview(solution),
        "entities.md": _generate_entities(
            parsed.get("entities", []),
            relationships=parsed.get("entity_relationships", []),
        ),
        "workflows.md": _generate_workflows(parsed.get("workflows", [])),
        "web-resources.md": _generate_webresources(
            parsed.get("webresources", []),
            entities=parsed.get("entities", []),
            app_modules=parsed.get("app_modules", []),
        ),
        "environment-variables.md": _generate_env_vars(
            parsed.get("env_vars", []),
            workflows=parsed.get("workflows", []),
        ),
        "security-roles.md": _generate_roles(
            parsed.get("roles", []),
            solution_entities=[e["name"] for e in parsed.get("entities", [])],
        ),
        "relationships.md": _generate_relationships(parsed.get("entity_relationships", [])),
        "connection-references.md": _generate_connection_refs(
            parsed.get("connection_references", []),
            workflows=parsed.get("workflows", []),
        ),
        "app-modules.md": _generate_app_modules(
            parsed.get("app_modules", []),
            entities=parsed.get("entities", []),
            roles=parsed.get("roles", []),
            sitemaps=parsed.get("sitemaps", []),
            webresources=parsed.get("webresources", []),
        ),
        "plugins.md": _generate_plugins(parsed.get("plugins", {})),
        "pcf-controls.md": _generate_controls(parsed.get("controls", [])),
    }

    option_sets = parsed.get("global_option_sets", [])
    if option_sets:
        docs["global-option-sets.md"] = _generate_global_option_sets(
            option_sets,
            entities=parsed.get("entities", []),
        )

    return docs


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _h(level: int, text: str) -> str:
    return f"{'#' * level} {text}"


def _table(headers: list[str], rows: list[list[str]]) -> str:
    header_row = "| " + " | ".join(headers) + " |"
    sep_row = "|" + "|".join(["---"] * len(headers)) + "|"
    data_rows = ["| " + " | ".join(str(c) for c in row) + " |" for row in rows]
    return "\n".join([header_row, sep_row] + data_rows)


def _badge(text: str) -> str:
    return f"`{text}`"


# ---------------------------------------------------------------------------
# Index / README
# ---------------------------------------------------------------------------

def _generate_index(
    parsed: dict[str, Any],
    solution_name: str,
    warnings: list[str] | None = None,
) -> str:
    sol = parsed.get("solution", {})
    lines = [
        _h(1, f"{sol.get('display_name', solution_name)} — Solution Documentation"),
        "",
        "> Generated by **Dataverse Solution Documenter**",
        "",
    ]

    parse_warnings = warnings or []
    if parse_warnings:
        lines += [
            _h(2, "⚠️ Parse Warnings"),
            "",
            "> The following components could not be fully parsed. "
            "Details may be missing for the items below.",
            "",
        ]
        lines += [f"- {w}" for w in parse_warnings]
        lines += ["", "---", ""]

    lines += [
        _h(2, "Contents"),
        "",
        _table(
            ["Document", "Description"],
            [
                ["[Solution Overview](solution-overview.md)", "Metadata, publisher, version, component summary"],
                ["[Entities & Tables](entities.md)", f"Entities ({len(parsed.get('entities', []))})"],
                ["[Workflows](workflows.md)", f"Workflows ({len(parsed.get('workflows', []))})"],
                ["[Web Resources](web-resources.md)", f"Web resources ({len(parsed.get('webresources', []))})"],
                ["[Environment Variables](environment-variables.md)", f"Environment variable definitions ({len(parsed.get('env_vars', []))})"],
                ["[Security Roles](security-roles.md)", f"Roles ({len(parsed.get('roles', []))})"],
                ["[Entity Relationships](relationships.md)", f"Relationships ({len(parsed.get('entity_relationships', []))})"],
                ["[Connection References](connection-references.md)", f"Connection references ({len(parsed.get('connection_references', []))})"],
                ["[App Modules](app-modules.md)", f"Model-driven apps ({len(parsed.get('app_modules', []))})"],
                ["[Plugin Assemblies](plugins.md)", f"Plugin assemblies ({len(parsed.get('plugins', {}).get('assemblies', []))}) / Steps ({len(parsed.get('plugins', {}).get('steps', []))})"],
                ["[PCF Controls](pcf-controls.md)", f"Custom controls ({len(parsed.get('controls', []))})"],
            ],
        ),
        "",
        "---",
        "",
        f"**Solution:** {_badge(sol.get('unique_name', 'N/A'))}  ",
        f"**Version:** {_badge(sol.get('version', 'N/A'))}  ",
        f"**Publisher:** {sol.get('publisher_name', 'N/A')} ({_badge(sol.get('publisher_prefix', ''))})  ",
        f"**Managed:** {'Yes' if sol.get('is_managed') == '1' else 'No'}  ",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Solution Overview
# ---------------------------------------------------------------------------

def _generate_solution_overview(solution: dict[str, Any]) -> str:
    lines = [
        _h(1, "Solution Overview"),
        "",
        _h(2, "Metadata"),
        "",
        _table(
            ["Field", "Value"],
            [
                ["Unique Name", _badge(solution.get("unique_name", ""))],
                ["Display Name", solution.get("display_name", "")],
                ["Version", _badge(solution.get("version", ""))],
                ["Managed", "Yes" if solution.get("is_managed") == "1" else "No"],
                ["Publisher", solution.get("publisher_name", "")],
                ["Publisher Unique Name", _badge(solution.get("publisher_unique_name", ""))],
                ["Customization Prefix", _badge(solution.get("publisher_prefix", ""))],
                ["Option Value Prefix", solution.get("publisher_option_prefix", "")],
                ["Total Root Components", str(solution.get("component_count", 0))],
            ],
        ),
        "",
    ]

    if solution.get("description"):
        lines += [_h(2, "Description"), "", solution["description"], ""]

    if solution.get("publisher_description"):
        lines += [_h(2, "Publisher Description"), "", solution["publisher_description"], ""]

    component_types = solution.get("component_types", {})
    if component_types:
        lines += [
            _h(2, "Component Breakdown"),
            "",
            _table(
                ["Component Type", "Count"],
                [[ctype, str(count)] for ctype, count in sorted(component_types.items())],
            ),
            "",
        ]

    missing_deps = solution.get("missing_dependencies", [])
    if missing_deps:
        lines += [
            _h(2, "Dependencies & Prerequisites"),
            "",
            "> External components and solutions required in target environments prior to solution import.",
            "",
        ]
        dep_rows = []
        for d in missing_deps:
            dep_on = d.get("dependent_schema") or "Solution Root"
            if d.get("dependent_parent"):
                dep_on = f"{d['dependent_parent']}.{dep_on}"
            dep_rows.append([
                _badge(d.get("required_schema") or d.get("required_display", "")),
                d.get("required_type", ""),
                d.get("required_solution", ""),
                _badge(dep_on) if dep_on != "Solution Root" else dep_on,
            ])
        lines += [
            _table(
                ["Required Component", "Type", "Required Solution", "Dependent Component"],
                dep_rows,
            ),
            "",
        ]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Entities
# ---------------------------------------------------------------------------

def _generate_entities(
    entities: list[dict[str, Any]],
    relationships: list[dict[str, Any]] | None = None,
) -> str:
    lines = [_h(1, "Entities & Tables"), ""]

    if not entities:
        lines.append("_No entities found in customizations.xml._")
        return "\n".join(lines)

    lines += [f"**Total entities:** {len(entities)}", ""]

    # Pre-calculate relationships per entity
    rels = relationships or []
    rels_by_entity: dict[str, list[dict[str, Any]]] = {}
    for r in rels:
        e1 = (r.get("entity1") or "").lower()
        e2 = (r.get("entity2") or "").lower()
        if e1:
            rels_by_entity.setdefault(e1, []).append(r)
        if e2 and e2 != e1:
            rels_by_entity.setdefault(e2, []).append(r)

    # Summary table
    lines += [
        _h(2, "Summary"),
        "",
        _table(
            ["Display Name", "Schema Name", "Attributes", "Forms", "Views"],
            [
                [
                    f"[{e.get('display_name') or e.get('name', '')}](#{(e.get('display_name') or e.get('name', '')).lower().replace(' ', '-').replace('_', '-')})",
                    _badge(e.get("name", "")),
                    str(len(e.get("attributes", []))),
                    str(len(e.get("forms", []))),
                    str(len(e.get("views", []))),
                ]
                for e in entities
            ],
        ),
        "",
        "---",
        "",
    ]

    for entity in entities:
        display = entity.get("display_name") or entity.get("name", "Unknown")
        schema = entity.get("name", "")
        lines += [_h(2, display), ""]

        lines += [
            _table(
                ["Field", "Value"],
                [
                    ["Schema Name", _badge(schema)],
                    ["Display Name", display],
                    ["Collection Name", entity.get("collection_name", "")],
                    ["Description", entity.get("description", "")],
                ],
            ),
            "",
        ]

        attrs = entity.get("attributes", [])
        if attrs:
            lines += [_h(3, "Attributes"), ""]
            attr_rows = []
            for attr in attrs:
                req = attr.get("required", "none")
                req_icon = "✅" if req == "required" else ("⚠️" if req == "systemrequired" else "")
                options_str = ""
                if attr.get("options"):
                    options_str = "; ".join(
                        f"{o['value']}: {o['label']}" for o in attr["options"][:5]
                    )
                    if len(attr["options"]) > 5:
                        options_str += f" (+{len(attr['options'])-5} more)"
                elif attr.get("optionset_name"):
                    options_str = f"OptionSet: `{attr['optionset_name']}`"
                attr_rows.append([
                    _badge(attr.get("name", "")),
                    attr.get("display_name", ""),
                    attr.get("type", ""),
                    req_icon or req,
                    options_str,
                ])
            lines += [
                _table(["Schema Name", "Display Name", "Type", "Required", "Options / References"], attr_rows),
                "",
            ]

        forms = entity.get("forms", [])
        if forms:
            lines += [
                _h(3, "Forms"),
                "",
                _table(
                    ["Name", "ID", "Version", "Active"],
                    [
                        [
                            f.get("name", ""),
                            _badge(f.get("id", "")),
                            f.get("version", ""),
                            "✅" if f.get("active") else "❌",
                        ]
                        for f in forms
                    ],
                ),
                "",
            ]

        views = entity.get("views", [])
        if views:
            lines += [
                _h(3, "Views"),
                "",
                _table(
                    ["Name", "Type"],
                    [[v.get("name", ""), v.get("type", "")] for v in views],
                ),
                "",
            ]

        # Entity Dependencies & References
        ent_rels = rels_by_entity.get(schema.lower(), [])
        form_libs = []
        for f in forms:
            for lib in f.get("libraries", []):
                if lib not in form_libs:
                    form_libs.append(lib)

        opt_sets_used = []
        for attr in attrs:
            opt_name = attr.get("optionset_name")
            if opt_name and opt_name not in opt_sets_used:
                opt_sets_used.append(opt_name)

        if ent_rels or form_libs or opt_sets_used:
            lines += [_h(3, "Dependencies & References"), ""]
            if ent_rels:
                lines += [
                    f"**Relationships ({len(ent_rels)}):**  ",
                ]
                rel_rows = []
                for r in ent_rels:
                    other_ent = r.get("entity2") if (r.get("entity1") or "").lower() == schema.lower() else r.get("entity1")
                    rel_rows.append([
                        _badge(r.get("name", "")),
                        r.get("type", "") or "OneToMany",
                        _badge(other_ent or "—"),
                        _badge(r.get("referencing_attribute", "")) if r.get("referencing_attribute") else "—",
                    ])
                lines += [
                    _table(["Relationship", "Type", "Related Table", "Lookup Attribute"], rel_rows),
                    "",
                ]

            if opt_sets_used:
                lines += [
                    f"**Referenced Option Sets:** {', '.join(_badge(o) for o in opt_sets_used)}  ",
                ]
            if form_libs:
                lines += [
                    f"**Form Web Resources (Scripts/Libraries):** {', '.join(_badge(lib) for lib in form_libs)}  ",
                ]
            lines.append("")

        lines += ["---", ""]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Workflows
# ---------------------------------------------------------------------------

def _generate_workflows(workflows: list[dict[str, Any]]) -> str:
    lines = [_h(1, "Workflows"), ""]

    if not workflows:
        lines.append("_No workflows found in this solution._")
        return "\n".join(lines)

    lines += [f"**Total workflows:** {len(workflows)}", ""]

    # Group by category
    by_category: dict[str, list] = {}
    for wf in workflows:
        cat = wf.get("category", "Unknown")
        by_category.setdefault(cat, []).append(wf)

    for category, wfs in sorted(by_category.items()):
        lines += [_h(2, category), ""]
        for wf in wfs:
            lines += [_h(3, wf.get("name", "Unnamed")), ""]

            rows: list[list[str]] = [
                ["Category", wf.get("category", "")],
                ["Primary Entity", wf.get("primary_entity", "") or "N/A"],
                ["State", wf.get("state", "")],
                ["Introduced Version", wf.get("introduced_version", "")],
            ]
            if wf.get("description"):
                rows.insert(0, ["Description", wf["description"]])

            trigger_flags = []
            if wf.get("on_demand"):
                trigger_flags.append("On Demand")
            if wf.get("trigger_on_create"):
                trigger_flags.append("On Create")
            if wf.get("trigger_on_delete"):
                trigger_flags.append("On Delete")
            if trigger_flags:
                rows.append(["Classic Trigger", ", ".join(trigger_flags)])

            lines += [_table(["Field", "Value"], rows), ""]

            if wf.get("triggers"):
                lines += [
                    f"**Triggers:** {', '.join(_badge(t) for t in wf['triggers'])}  ",
                ]
            if wf.get("actions"):
                lines += [
                    f"**Actions:** {', '.join(_badge(a) for a in wf['actions'])}  ",
                ]
            if wf.get("connection_refs"):
                lines += [
                    f"**Connection References:** {', '.join(_badge(c) for c in wf['connection_refs'])}  ",
                ]
            if wf.get("env_vars"):
                lines += [
                    f"**Environment Variables:** {', '.join(_badge(ev) for ev in wf['env_vars'])}  ",
                ]
            if wf.get("dataverse_entities"):
                lines += [
                    f"**Dataverse Tables Accessed:** {', '.join(_badge(de) for de in wf['dataverse_entities'])}  ",
                ]

            if wf.get("file"):
                lines += [f"**Source File:** `{wf['file']}`  "]

            lines.append("")

        lines += ["---", ""]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Web Resources
# ---------------------------------------------------------------------------

def _generate_webresources(
    webresources: list[dict[str, Any]],
    entities: list[dict[str, Any]] | None = None,
    app_modules: list[dict[str, Any]] | None = None,
) -> str:
    lines = [_h(1, "Web Resources"), ""]

    if not webresources:
        lines.append("_No web resources found in this solution._")
        return "\n".join(lines)

    lines += [f"**Total web resources:** {len(webresources)}", ""]

    lines += [
        _table(
            ["Name", "Display Name", "Type", "Size", "Introduced Version"],
            [
                [
                    _badge(wr.get("name", "")),
                    wr.get("display_name", ""),
                    wr.get("type", ""),
                    f"{wr.get('size_bytes', 0) / 1024:.1f} KB" if wr.get("size_bytes") else "—",
                    wr.get("introduced_version", ""),
                ]
                for wr in webresources
            ],
        ),
        "",
    ]

    # Check for usage across entities / forms
    ents = entities or []
    wr_usage: dict[str, list[str]] = {}
    for e in ents:
        e_name = e.get("display_name") or e.get("name", "")
        for f in e.get("forms", []):
            f_name = f.get("name", "Form")
            for lib in f.get("libraries", []):
                wr_usage.setdefault(lib.lower(), []).append(f"{e_name} ({f_name})")

    if any(wr_usage.values()):
        lines += [
            _h(2, "Web Resource Form Dependencies"),
            "",
            "> Web resources loaded into entity form scripts or client libraries.",
            "",
        ]
        usage_rows = []
        for wr in webresources:
            wr_name = wr.get("name", "")
            users = wr_usage.get(wr_name.lower(), [])
            if users:
                usage_rows.append([
                    _badge(wr_name),
                    wr.get("type", ""),
                    ", ".join(users),
                ])
        if usage_rows:
            lines += [
                _table(["Web Resource", "Type", "Referenced By (Entity & Form)"], usage_rows),
                "",
            ]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Environment Variables
# ---------------------------------------------------------------------------

def _generate_env_vars(
    env_vars: list[dict[str, Any]],
    workflows: list[dict[str, Any]] | None = None,
) -> str:
    lines = [_h(1, "Environment Variables"), ""]

    if not env_vars:
        lines.append("_No environment variables found in this solution._")
        return "\n".join(lines)

    lines += [f"**Total environment variables:** {len(env_vars)}", ""]

    # Map env var schema names to consuming workflows
    wfs = workflows or []
    consumers: dict[str, list[str]] = {}
    for wf in wfs:
        wf_name = wf.get("name", "Workflow")
        for ev_schema in wf.get("env_vars", []):
            consumers.setdefault(ev_schema.lower(), []).append(wf_name)

    for ev in env_vars:
        schema_name = ev.get("schema_name", "")
        lines += [_h(2, ev.get("display_name") or schema_name or "Unknown"), ""]

        rows = [
            ["Schema Name", _badge(schema_name)],
            ["Display Name", ev.get("display_name", "")],
            ["Type", ev.get("type", "")],
            ["Required", "Yes" if ev.get("is_required") else "No"],
            ["Secret", "Yes" if ev.get("is_secret") else "No"],
            ["Introduced Version", ev.get("introduced_version", "")],
        ]
        if ev.get("description"):
            rows.insert(2, ["Description", ev["description"]])

        flow_users = consumers.get(schema_name.lower(), [])
        if flow_users:
            rows.append(["Referenced by Workflows", ", ".join(_badge(u) for u in flow_users)])

        lines += [_table(["Field", "Value"], rows), "", "---", ""]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Security Roles
# ---------------------------------------------------------------------------

# Access level display: symbol + label
_LEVEL_SYMBOL = {
    "Global":  "🌐 Global",
    "Deep":    "🔵 Deep",
    "Local":   "🟡 Local",
    "Basic":   "🟢 Basic",
    "None":    "⬜ None",
}
_LEVEL_RANK = {"Global": 4, "Deep": 3, "Local": 2, "Basic": 1, "None": 0, "": -1}

_ACTIONS = ["Create", "Read", "Write", "Delete", "Append", "AppendTo", "Assign", "Share"]


def _level(val: str) -> str:
    return _LEVEL_SYMBOL.get(val, val or "—")


def _generate_roles(roles: list[dict[str, Any]], solution_entities: list[str] | None = None) -> str:
    lines = [_h(1, "Security Roles"), ""]

    if not roles:
        lines.append("_No security roles found in this solution._")
        return "\n".join(lines)

    lines += [
        f"**Total security roles:** {len(roles)}",
        "",
        "| Level | Meaning |",
        "|---|---|",
        "| 🌐 Global | Entire organisation |",
        "| 🔵 Deep | Business unit + child units |",
        "| 🟡 Local | Own business unit only |",
        "| 🟢 Basic | Records owned by the user |",
        "",
        "---",
        "",
    ]

    # ---- Section 1: Cross-role comparison for solution entities ----
    sol_ents = solution_entities or []
    if sol_ents and len(roles) > 1:
        lines += [
            _h(2, "Cross-Role Comparison — Solution Entities"),
            "",
            "> Showing **Read** access level per role for entities defined in this solution.",
            "",
        ]
        role_names = [r["name"] for r in roles]
        header = ["Entity"] + role_names
        sep = ["---"] * len(header)
        rows = []
        for ent in sol_ents:
            row = [f"`{ent}`"]
            for role in roles:
                ep = role.get("entity_privileges", {})
                # Case-insensitive lookup
                match = next(
                    (ep[k] for k in ep if k.lower() == ent.lower()), {}
                )
                read_level = match.get("Read", "—")
                row.append(_level(read_level) if read_level != "—" else "—")
            rows.append(row)

        lines.append("| " + " | ".join(header) + " |")
        lines.append("|" + "|".join(sep) + "|")
        for row in rows:
            lines.append("| " + " | ".join(row) + " |")
        lines += ["", "---", ""]

    # ---- Section 2: Full entity privilege matrix per role ----
    for role in roles:
        role_name = role.get("name", "Unknown")
        ep: dict[str, dict[str, str]] = role.get("entity_privileges", {})
        misc: dict[str, str] = role.get("misc_privileges", {})

        lines += [_h(2, role_name), ""]

        # -- 2a: Solution entities full CRUD matrix --
        if sol_ents:
            lines += [
                _h(3, "Solution Entities"),
                "",
                "| Entity | " + " | ".join(_ACTIONS) + " |",
                "|---|" + "|".join(["---"] * len(_ACTIONS)) + "|",
            ]
            for ent in sol_ents:
                match = next((ep[k] for k in ep if k.lower() == ent.lower()), {})
                cells = [_level(match.get(a, "")) if match.get(a) else "—" for a in _ACTIONS]
                lines.append(f"| `{ent}` | " + " | ".join(cells) + " |")
            lines.append("")

        # -- 2b: All other entities grouped by access level --
        lines += [_h(3, "All Entity Privileges"), ""]

        # Separate solution entities from others, group remainder by level profile
        sol_ents_lower = {e.lower() for e in sol_ents}
        other_entities = {k: v for k, v in ep.items() if k.lower() not in sol_ents_lower}

        if other_entities:
            # Group by highest access level (Read if present, else max of all)
            by_level: dict[str, list[tuple[str, dict]]] = {
                "Global": [], "Deep": [], "Local": [], "Basic": [], "Other": []
            }
            for ent_name, actions in sorted(other_entities.items()):
                read_level = actions.get("Read", "")
                top_level = read_level or max(
                    actions.values(),
                    key=lambda x: _LEVEL_RANK.get(x, -1),
                    default=""
                )
                bucket = top_level if top_level in by_level else "Other"
                by_level[bucket].append((ent_name, actions))

            for level_name, ents in by_level.items():
                if not ents:
                    continue
                lines += [
                    f"**{_LEVEL_SYMBOL.get(level_name, level_name)} access** ({len(ents)} entities)",
                    "",
                    "<details><summary>Expand</summary>",
                    "",
                    "| Entity | " + " | ".join(_ACTIONS) + " |",
                    "|---|" + "|".join(["---"] * len(_ACTIONS)) + "|",
                ]
                for ent_name, actions in ents:
                    cells = [_level(actions.get(a, "")) if actions.get(a) else "—" for a in _ACTIONS]
                    lines.append(f"| `{ent_name}` | " + " | ".join(cells) + " |")
                lines += ["", "</details>", ""]
        else:
            lines.append("_No additional entity privileges._\n")

        # -- 2c: Misc / non-entity privileges --
        if misc:
            lines += [
                _h(3, "Miscellaneous Privileges"),
                "",
                f"**{len(misc)} non-entity privileges** (feature access, system actions)",
                "",
                "| Privilege | Level |",
                "|---|---|",
            ]
            for priv_name, level in sorted(misc.items()):
                lines.append(f"| {priv_name} | {_level(level)} |")
            lines.append("")

        # -- 2d: Summary counts --
        total_entity_privs = sum(len(v) for v in ep.values())
        lines += [
            _h(3, "Summary"),
            "",
            _table(
                ["Metric", "Count"],
                [
                    ["Entities with privileges", str(len(ep))],
                    ["Total entity privilege grants", str(total_entity_privs)],
                    ["Miscellaneous privilege grants", str(len(misc))],
                ],
            ),
            "",
            "---",
            "",
        ]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Entity Relationships
# ---------------------------------------------------------------------------

def _generate_relationships(relationships: list[dict[str, Any]]) -> str:
    lines = [_h(1, "Entity Relationships"), ""]

    if not relationships:
        lines.append("_No entity relationships found in this solution._")
        return "\n".join(lines)

    lines += [f"**Total relationships:** {len(relationships)}", ""]

    lines += [
        _table(
            ["Relationship Name", "Type", "Entity 1 (Referencing)", "Entity 2 (Referenced)", "Lookup Attribute"],
            [
                [
                    _badge(r.get("name", "")),
                    r.get("type", "") or "OneToMany",
                    _badge(r.get("entity1", "")) if r.get("entity1") else "—",
                    _badge(r.get("entity2", "")) if r.get("entity2") else "—",
                    _badge(r.get("referencing_attribute", "")) if r.get("referencing_attribute") else "—",
                ]
                for r in relationships
            ],
        ),
        "",
    ]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Connection References
# ---------------------------------------------------------------------------

def _generate_connection_refs(
    refs: list[dict[str, Any]],
    workflows: list[dict[str, Any]] | None = None,
) -> str:
    lines = [_h(1, "Connection References"), ""]

    if not refs:
        lines.append("_No connection references found in this solution._")
        return "\n".join(lines)

    lines += [
        f"**Total connection references:** {len(refs)}",
        "",
    ]

    # Map connection references to consuming workflows
    wfs = workflows or []
    consumers: dict[str, list[str]] = {}
    for wf in wfs:
        wf_name = wf.get("name", "Workflow")
        for cr_logical in wf.get("connection_refs", []):
            consumers.setdefault(cr_logical.lower(), []).append(wf_name)

    ref_rows = []
    for r in refs:
        logical_name = r.get("logical_name", "")
        flow_users = consumers.get(logical_name.lower(), [])
        flows_str = ", ".join(_badge(u) for u in flow_users) if flow_users else "—"
        ref_rows.append([
            _badge(logical_name),
            r.get("display_name", ""),
            _badge(r.get("connector_id", "")) if r.get("connector_id") else "—",
            flows_str,
        ])

    lines += [
        _table(
            ["Logical Name", "Display Name", "Connector", "Referenced by Workflows"],
            ref_rows,
        ),
        "",
    ]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# App Modules
# ---------------------------------------------------------------------------

def _generate_app_modules(
    apps: list[dict[str, Any]],
    entities: list[dict[str, Any]] | None = None,
    roles: list[dict[str, Any]] | None = None,
    sitemaps: list[dict[str, Any]] | None = None,
    webresources: list[dict[str, Any]] | None = None,
) -> str:
    lines = [_h(1, "Model-Driven Apps (App Modules)"), ""]

    if not apps:
        lines.append("_No app modules found in this solution._")
        return "\n".join(lines)

    lines += [f"**Total Model-Driven Apps:** {len(apps)}", ""]

    # Build lookup dictionaries
    ents_list = entities or []
    form_map: dict[str, tuple[str, str]] = {}
    view_map: dict[str, tuple[str, str]] = {}
    entity_display_map: dict[str, str] = {}

    for e in ents_list:
        e_schema = e.get("name", "")
        e_disp = e.get("display_name") or e_schema
        entity_display_map[e_schema.lower()] = e_disp
        for f in e.get("forms", []):
            f_id = (f.get("id") or "").lower()
            if f_id:
                form_map[f_id] = (e_disp, f.get("name") or "Unnamed Form")
        for v in e.get("views", []):
            v_id = (v.get("id") or "").lower()
            if v_id:
                view_map[v_id] = (e_disp, v.get("name") or "Unnamed View")

    all_sitemaps = sitemaps or []

    for app in apps:
        app_name = app.get("display_name") or app.get("unique_name", "Unknown")
        lines += [_h(2, app_name), ""]
        rows = [
            ["Unique Name", _badge(app.get("unique_name", ""))],
            ["Display Name", app_name],
        ]
        if app.get("description"):
            rows.append(["Description", app["description"]])

        lines += [_table(["Field", "Value"], rows), ""]

        # ---- Sitemap Navigation Hierarchy ----
        if all_sitemaps:
            lines += [_h(3, "Sitemap Navigation Structure"), ""]
            for sm_idx, sm in enumerate(all_sitemaps, 1):
                for area in sm.get("areas", []):
                    lines += [f"#### Area: **{area.get('title', 'Area')}**", ""]
                    for group in area.get("groups", []):
                        lines += [f"- **Group: {group.get('title', 'Group')}**"]
                        for sub in group.get("subareas", []):
                            target = ""
                            if sub.get("entity"):
                                e_name = entity_display_map.get(sub["entity"].lower(), sub["entity"])
                                target = f"Table: `{sub['entity']}` ({e_name})"
                            elif sub.get("url"):
                                target = f"URL: `{sub['url']}`"
                            else:
                                target = sub.get("id", "")
                            lines += [f"  - `{sub.get('title', 'SubArea')}` → {target}"]
                    lines.append("")

        # ---- Included Entities / Tables ----
        included_ents = app.get("entities", [])
        if included_ents:
            lines += [_h(3, f"Included Tables ({len(included_ents)})"), ""]
            ent_rows = []
            for e_schema in sorted(included_ents):
                disp = entity_display_map.get(e_schema.lower(), e_schema)
                ent_rows.append([_badge(e_schema), disp])
            lines += [_table(["Table Schema Name", "Display Name"], ent_rows), ""]

        # ---- Included Forms ----
        form_ids = app.get("form_ids", [])
        if form_ids:
            lines += [_h(3, f"Included Forms ({len(form_ids)})"), ""]
            form_rows = []
            for fid in form_ids:
                if fid in form_map:
                    tbl, fname = form_map[fid]
                    form_rows.append([tbl, fname, _badge(fid)])
                else:
                    form_rows.append(["External / System Table", "System Form", _badge(fid)])
            lines += [_table(["Table", "Form Name", "Form ID"], form_rows), ""]

        # ---- Included Views ----
        view_ids = app.get("view_ids", [])
        if view_ids:
            lines += [_h(3, f"Included Views ({len(view_ids)})"), ""]
            view_rows = []
            for vid in view_ids:
                if vid in view_map:
                    tbl, vname = view_map[vid]
                    view_rows.append([tbl, vname, _badge(vid)])
                else:
                    view_rows.append(["External / System Table", "System View", _badge(vid)])
            lines += [_table(["Table", "View Name", "View ID"], view_rows), ""]

        # ---- Included Dashboards ----
        dash_ids = app.get("dashboard_ids", [])
        if dash_ids:
            lines += [_h(3, f"Included Dashboards ({len(dash_ids)})"), ""]
            dash_rows = []
            for did in dash_ids:
                if did in form_map:
                    tbl, dname = form_map[did]
                    dash_rows.append([dname, _badge(did)])
                else:
                    dash_rows.append(["Dashboard", _badge(did)])
            lines += [_table(["Dashboard Name", "Dashboard ID"], dash_rows), ""]

        # ---- Included Business Process Flows ----
        bpf_ids = app.get("bpf_ids", [])
        if bpf_ids:
            lines += [_h(3, f"Included Business Process Flows ({len(bpf_ids)})"), ""]
            bpf_rows = []
            for bid in bpf_ids:
                disp = entity_display_map.get(bid.lower(), bid)
                bpf_rows.append([disp, _badge(bid)])
            lines += [_table(["BPF / Process Name", "Process ID"], bpf_rows), ""]

        lines += ["---", ""]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Global Option Sets
# ---------------------------------------------------------------------------

def _generate_global_option_sets(
    option_sets: list[dict[str, Any]],
    entities: list[dict[str, Any]] | None = None,
) -> str:
    lines = [_h(1, "Global Option Sets"), ""]

    if not option_sets:
        lines.append("_No global option sets found in this solution._")
        return "\n".join(lines)

    # Map option set names to consuming entities & attributes
    ents = entities or []
    consumers: dict[str, list[str]] = {}
    for e in ents:
        e_name = e.get("display_name") or e.get("name", "")
        for attr in e.get("attributes", []):
            opt_name = attr.get("optionset_name")
            if opt_name:
                consumers.setdefault(opt_name.lower(), []).append(f"{e_name}.{attr.get('name', '')}")

    for os_data in option_sets:
        os_schema = os_data.get("name", "")
        name = os_data.get("display_name") or os_schema or "Unknown"
        lines += [_h(2, name), ""]

        used_by = consumers.get(os_schema.lower(), [])
        if used_by:
            lines += [f"**Referenced by Attributes:** {', '.join(_badge(u) for u in used_by)}  ", ""]

        if os_data.get("options"):
            lines += [
                _table(["Value", "Label"], [[o["value"], o["label"]] for o in os_data["options"]]),
                "",
            ]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Plugins
# ---------------------------------------------------------------------------

def _generate_plugins(plugins: dict[str, Any]) -> str:
    lines = [_h(1, "Plugin Assemblies & Step Registrations"), ""]

    assemblies = plugins.get("assemblies", []) if isinstance(plugins, dict) else []
    steps = plugins.get("steps", []) if isinstance(plugins, dict) else []

    if not assemblies and not steps:
        lines.append("_No plugin assemblies found in this solution._")
        return "\n".join(lines)

    lines += [
        f"**Assemblies:** {len(assemblies)}  ",
        f"**Step registrations:** {len(steps)}",
        "",
    ]

    # ---- Section 1: Assemblies ----
    if assemblies:
        lines += [_h(2, "Assemblies"), ""]
        for asm in assemblies:
            lines += [_h(3, asm.get("name", "Unknown")), ""]
            lines += [
                _table(
                    ["Field", "Value"],
                    [
                        ["Assembly Name", _badge(asm.get("name", ""))],
                        ["Version", _badge(asm.get("version", ""))],
                        ["Isolation Mode", asm.get("isolation_mode", "")],
                        ["Introduced Version", asm.get("introduced_version", "")],
                        ["File", f"`{asm.get('file', '')}`" if asm.get("file") else "—"],
                    ],
                ),
                "",
            ]

            plugin_types = asm.get("plugin_types", [])
            if plugin_types:
                lines += [
                    _h(4, "Plugin Types"),
                    "",
                    _table(
                        ["Class Name", "ID"],
                        [[_badge(pt.get("name", "")), pt.get("id", "")] for pt in plugin_types],
                    ),
                    "",
                ]
            lines += ["---", ""]

    # ---- Section 2: Step Registrations ----
    if steps:
        lines += [_h(2, "Step Registrations"), ""]

        # Group by assembly
        by_asm: dict[str, list] = {}
        for step in steps:
            asm_name = step.get("assembly_name") or "Unassigned"
            by_asm.setdefault(asm_name, []).append(step)

        for asm_name, asm_steps in by_asm.items():
            lines += [_h(3, asm_name), ""]
            rows = []
            for s in asm_steps:
                name = s.get("name", "")
                # Shorten step name for table (strip assembly prefix if present)
                short_name = name.split(":")[-1].strip() if ":" in name else name
                rows.append([
                    short_name,
                    _badge(s.get("primary_entity", "")) if s.get("primary_entity") else "—",
                    s.get("stage", ""),
                    s.get("mode", ""),
                    s.get("rank", ""),
                    s.get("deployment", ""),
                    _badge(s.get("filtering_attributes")) if s.get("filtering_attributes") else "—",
                ])
            lines += [
                _table(
                    ["Step", "Entity", "Stage", "Mode", "Rank", "Deployment", "Filtering Attrs"],
                    rows,
                ),
                "",
                "---",
                "",
            ]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# PCF Controls
# ---------------------------------------------------------------------------

def _generate_controls(controls: list[dict[str, Any]]) -> str:
    lines = [_h(1, "PCF Custom Controls"), ""]

    if not controls:
        lines.append("_No PCF custom controls found in this solution._")
        return "\n".join(lines)

    lines += [f"**Total controls:** {len(controls)}", ""]

    # Summary table
    lines += [
        _h(2, "Summary"),
        "",
        _table(
            ["Control Name", "Namespace", "Version", "Type", "Properties", "Total Size"],
            [
                [
                    c.get("display_name") or c.get("name", ""),
                    _badge(c.get("namespace", "")),
                    c.get("version", ""),
                    c.get("control_type", ""),
                    str(len(c.get("properties", []))),
                    f"{c.get('total_size_bytes', 0) / 1024:.0f} KB",
                ]
                for c in controls
            ],
        ),
        "",
        "---",
        "",
    ]

    for ctrl in controls:
        display = ctrl.get("display_name") or ctrl.get("name", "Unknown")
        lines += [_h(2, display), ""]

        lines += [
            _table(
                ["Field", "Value"],
                [
                    ["Name", _badge(ctrl.get("name", ""))],
                    ["Namespace", _badge(ctrl.get("namespace", ""))],
                    ["Constructor", _badge(ctrl.get("constructor", ""))],
                    ["Version", ctrl.get("version", "")],
                    ["Control Type", ctrl.get("control_type", "")],
                    ["API Version", ctrl.get("api_version", "")],
                    ["Built By", ctrl.get("built_by", "")],
                    ["Total Size", f"{ctrl.get('total_size_bytes', 0) / 1024:.0f} KB"],
                ],
            ),
            "",
        ]

        if ctrl.get("description"):
            lines += [f"> {ctrl['description']}", ""]

        props = ctrl.get("properties", [])
        if props:
            lines += [
                _h(3, "Properties"),
                "",
                _table(
                    ["Name", "Display Name", "Type", "Usage", "Required"],
                    [
                        [
                            _badge(p.get("name", "")),
                            p.get("display_name", ""),
                            p.get("type", ""),
                            p.get("usage", ""),
                            "✅" if p.get("required") else "—",
                        ]
                        for p in props
                    ],
                ),
                "",
            ]

        files = ctrl.get("files", [])
        if files:
            lines += [
                _h(3, "Bundled Files"),
                "",
                _table(
                    ["File", "Size"],
                    [
                        [f"`{f['path']}`", f"{f['size_bytes'] / 1024:.0f} KB"]
                        for f in files
                    ],
                ),
                "",
            ]

        lines += ["---", ""]

    return "\n".join(lines)

